<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ItsmyAccount-PC" name="automationframeworks.AdminInHouseStaff" tests="2" failures="0" timestamp="21 Oct 2017 09:20:18 GMT" time="12.585" errors="1">
  <testcase name="login" time="12.102" classname="automationframeworks.AdminInHouseStaff"/>
  <testcase name="AddMaintenanceMember" time="0.483" classname="automationframeworks.AdminInHouseStaff">
    <error type="org.testng.TestNGException" message="
The data provider is trying to pass 18 parameters but the method automationframeworks.AdminInHouseStaff#AddMaintenanceMember takes 19 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 18 parameters but the method automationframeworks.AdminInHouseStaff#AddMaintenanceMember takes 19 and TestNG is unable in inject a suitable object
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1249)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1118)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 18
	at org.testng.internal.Invoker.injectParameters(Invoker.java:1245)
	... 17 more
]]>
    </error>
  </testcase> <!-- AddMaintenanceMember -->
</testsuite> <!-- automationframeworks.AdminInHouseStaff -->
